package core.segment.integrity.enums;

public enum HealthStatus {
	HEALTHY, // EVERYTHING IS WORKING AS EXPECTED
	DEGRADED, // COULD MEAN METADATA_MISMTACH OR NEED OF COMPACTION (STILL USABLE)
	UNHEALTHY, // DATA CORRUPTION
	UNUSABLE, // JVM PERM, EXISTENCE
	UNKNOWN // INTIAL VALUE
}
