# 10MB
segment.max.size=10485760
# basically a volume
storage.root=storage
# segment pool directory - currently using only one hardcoded pool
segment.pool.dir.name=bucket-1
# segment pool directory metadata filename
segment.pool.metadata.filename=bucket.meta
